### ISSUE TITLE
Does not play well with spring-boot-devtools auto restart

### ISSUE THREAD

**Issue by hweichan** [coveooss/spring-boot-parameter-store-integration#10]
Hi!

Thanks for providing this easy to use library for accessing the AWS parameter store.
I have been using this successfully with encrypted data for production.

However, in development, when combined with the use of [spring-boot-devtools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-devtools-restart) for automatic reloading, it seems like values are not getting resolved.

So the observed behaviour is:
1. first time application startup - everything is fine
2. on automatic application reload - AWS parameter store values not resolved

My setup:

**`pom.xml`**

```
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-devtools</artifactId>
                    <optional>true</optional>
                </dependency>
...
			<dependency>
			    <groupId>com.coveo</groupId>
			    <artifactId>spring-boot-parameter-store-integration</artifactId>
			    <version>1.1.2</version>
			</dependency>
```

**`bootstrap.yml`**

```
awsParameterStorePropertySource:
  enabled: true
  haltBoot: true
```

I've also tried the config in `application.yml` as well as enabling the additional profile `awsParameterStorePropertySourceEnable`.

Any idea what needs to be done to make this work?

Thanks!

Regards,
Hwei

**Comment by wafisher** [comment]
I have the same thing with Spring Boot integration tests (JUnit 5) where the second invocation of the context won't launch with parameter store enabled. Seems like the same problem.

**Comment by wafisher** [comment]
This is almost certainly related to [this line](https://github.com/coveooss/spring-boot-parameter-store-integration/blob/master/src/main/java/com/coveo/configuration/parameterstore/ParameterStorePropertySourceEnvironmentPostProcessor.java#L30). Not sure why that's in there but it prevents the code from adding itself to the property sources the second time around.

**Comment by wafisher** [comment]
I fixed this with https://github.com/mtalirr/spring-boot-parameter-store-integration.

You can add by adding Jitpack to your repos (see docs https://github.com/jitpack/jitpack.io) and the following to your dependencies for now:

```
implementation 'com.github.mtalirr:spring-boot-parameter-store-integration:master-SNAPSHOT'
```

(you may need to reference the hash that `master` is on right now as the version instead of `master-SNAPSHOT`)

**Comment by fredboutin** [comment]
This line is there to support well spring cloud. See: https://github.com/coveooss/spring-boot-parameter-store-integration#spring-cloud.

I thought I had replied in this issue, but seems like I havent... 🤔 I had another work around, since the initialized variable is package protected for testing, you could set it to false after boot if you create a class in the same package. This is hackish, but should work. I'll take a look to see if I could add something to disable this.

**Comment by fredboutin** [comment]
With version 1.2.0 you can now set `awsParameterStorePropertySource.supportMultipleApplicationContexts` to `true` to support your use case. Let me know if you have any questions or if this does not do it for you.

I just published it in maven, should be available in a few hours tops.
