### ISSUE TITLE
Support resolving some values from AWS Secrets Manager

### ISSUE THREAD

**Issue by jospas** [coveooss/spring-boot-parameter-store-integration#14]
I have a customer using your integration and they love it!

They are have asked me how they might go about integrating this with AWS Secrets Manager for some parameters so they can support automated credential rolling with RDS for example. They like the ability to load all parameters under a prefix and Secrets Manager does not seem to support this.

They love the simplicity of your integration, but would like some parameters to be resolved via Secrets Manager.

Some suggested designs include:

1. Add a blessed tag to the SSM parameter which marks this as Secrets Manager resolved and the value of this tag is the ARN of the secret in Secrets Manager. The actual value of the parameter is junk.

2. Use a blessed prefix for values of the parameter and check these on load ie "SecretsManagerResolved:", if it matches, extract the Secrets Manager ARN from the remainder of the parameter value and load the value from Secrets Manager.

What do you think?

Josh

**Comment by fredboutin** [comment]
We might implement something for the Secret Manager eventually since we also use it. Although, this may not happen in the short term. If you use Spring Cloud, since this library was published, they have released something for both the parameter store and the secret manager. See their [documentation]( https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.1.0.RELEASE/single/spring-cloud-aws.html#_integrating_your_spring_cloud_application_with_the_aws_secrets_manage). We still have other plans (like multi-region) for this small library so I'm not saying it wont happen here too 😄If you want to try and submit a PR, we are also open to reviewing it.

**Comment by fredboutin** [comment]
I'll close this issue since we won't do this for now.
